name: Run Tests in Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build CI Docker image
        run: make build-ci

      - name: Run unit tests
        run: docker run --rm ci:latest pytest src/tests/test_prepare_data.py

      - name: Run FastAPI test
        run: pytest src/tests/test_api.py

