name: Run Tests in Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build CI Docker image
        run: make build-ci

      - name: Run unit tests
        run: docker run --rm ci:latest pytest src/tests/test_prepare_data.py

      - name: Run integration tests
        run: docker run --rm ci:latest pytest src/integration_tests/

      - name: Build and run prod container
        run: |
          docker build -f services/production/Dockerfile -t prod-test .
          docker run -d -p 8090:8090 --name fastapi-test prod-test
          sleep 5

      - name: Run FastAPI test
        run: |
          docker run --rm \
            --network host \
            -v ${{ github.workspace }}:/srv \
            -w /srv \
            ci:latest pytest src/tests/test_api.py

      - name: Cleanup containers
        run: docker rm -f fastapi-test || true