name: Run Tests in Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build CI Docker image
        run: make build-ci

      - name: Run unit tests
        run: docker run --rm ci:latest pytest src/tests/test_prepare_data.py

      - name: Smoke test FastAPI endpoint
        run: |
          sleep 3  # wait for API to be ready
          response=$(curl -s -w "%{http_code}" -o /tmp/api_response.json http://localhost:8090/delivery_time \
            -H "Content-Type: application/json" \
            -d '{"seller_zip_code_prefix": 9350, "customer_zip_code_prefix": 3149, "delivery_distance_km": 18}')
          
          if [ "$response" != "200" ]; then
            echo "❌ API returned unexpected status code: $response"
            exit 1
          fi

          if ! grep -q "delivery_time" /tmp/api_response.json; then
            echo "❌ Response does not contain 'delivery_time'"
            cat /tmp/api_response.json
            exit 1
          fi

          echo "✅ FastAPI endpoint passed basic check"

